name: Auto-lock inactive threads

on:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: dessant/lock-threads@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        issue-inactive-days: "7"
        issue-lock-reason: "resolved"
        issue-comment: >
          Because there has been no activity on this issue for 7 days since it was closed, it has
          been automatically locked. Please open a new issue if it requires a follow up.
        pr-inactive-days: "14"
        pr-lock-reason: "resolved"
        pr-comment: >
          Because there has been no activity on this PR for 14 days since it was merged, it has
          been automatically locked. Please open a new issue if it requires a follow up.
